// Execution Analytics Types - Verified vs Generated

// Verified (deterministic):
// - semantic_query: from a pre-defined semantic model
// - omni_query: from a pre-defined integration (OmniQuery)
// - automation: automation defined inline in agent config
//
// Not Verified (generated by LLM):
// - sql_generated: SQL generated by LLM (sql: None)
// - agent_tool: agent tool defined as an asset/artifact in the agent

export type ExecutionType =
  | "semantic_query"
  | "omni_query"
  | "sql_generated"
  | "workflow"
  | "agent_tool";

type ExecutionCategory = "verified" | "generated";

export interface ExecutionTypeInfo {
  type: ExecutionType;
  label: string;
  shortLabel: string;
  category: ExecutionCategory;
  color: string;
  chartColor: string;
  bgColor: string;
  borderColor: string;
  description: string;
}

export const EXECUTION_TYPES: Record<ExecutionType, ExecutionTypeInfo> = {
  semantic_query: {
    type: "semantic_query",
    label: "Semantic Query",
    shortLabel: "Semantic",
    category: "verified",
    color: "text-warning",
    chartColor: "--warning",
    bgColor: "bg-warning/10",
    borderColor: "border-warning/20",
    description: "Pre-defined semantic model query"
  },
  omni_query: {
    type: "omni_query",
    label: "OmniQuery",
    shortLabel: "OmniQuery",
    category: "verified",
    color: "text-vis-cyan",
    chartColor: "--vis-cyan",
    bgColor: "bg-vis-cyan/10 border-vis-cyan/20",
    borderColor: "border-vis-cyan/20",
    description: "Pre-defined integration query"
  },
  workflow: {
    type: "workflow",
    label: "Automation",
    shortLabel: "Automation",
    category: "verified",
    color: "text-vis-purple",
    chartColor: "--vis-purple",
    bgColor: "bg-vis-purple/10",
    borderColor: "border-vis-purple/20",
    description: "Automation defined inline in agent config"
  },
  sql_generated: {
    type: "sql_generated",
    label: "LLM SQL",
    shortLabel: "LLM SQL",
    category: "generated",
    color: "text-vis-orange",
    chartColor: "--vis-orange",
    bgColor: "bg-vis-orange/10 border-vis-orange/20",
    borderColor: "border-vis-orange/20",
    description: "SQL generated by LLM"
  },
  agent_tool: {
    type: "agent_tool",
    label: "Agent Tool",
    shortLabel: "Agent Tool",
    category: "generated",
    color: "text-info",
    chartColor: "--info",
    bgColor: "bg-info/10",
    borderColor: "border-info/20",
    description: "Agent tool asset with LLM-generated response"
  }
};

export interface ExecutionSummary {
  totalExecutions: number;
  verifiedCount: number;
  generatedCount: number;
  verifiedPercent: number;
  generatedPercent: number;
  successRateVerified: number;
  successRateGenerated: number;
  mostExecutedType: string;
  // Breakdown by type
  semanticQueryCount: number;
  omniQueryCount: number;
  sqlGeneratedCount: number;
  automationCount: number;
  agentToolCount: number;
}

export interface ExecutionTimeBucket {
  timestamp: string;
  verifiedCount: number;
  generatedCount: number;
  // Optional detailed breakdown
  semanticQueryCount?: number;
  omniQueryCount?: number;
  sqlGeneratedCount?: number;
  automationCount?: number;
  agentToolCount?: number;
}

// ── Latency percentiles ───────────────────────────────────────────────────
// GET /{projectId}/execution-analytics/percentiles?days=N
interface LatencyPercentiles {
  p50Ms: number;
  p95Ms: number;
  p99Ms: number;
  /**
   * Blended error rate (% of executions failing). Optional: NOT part of the
   * three agreed endpoint contracts — the UI falls back to the summary-derived
   * error rate when the backend omits it. See report deviation note.
   */
  errorRate?: number;
}

export interface PercentileTimePoint extends LatencyPercentiles {
  date: string;
}

export interface PercentilesResponse {
  overall: LatencyPercentiles;
  series: PercentileTimePoint[];
}

// ── Latency histogram ──────────────────────────────────────────────────────
// GET /{projectId}/execution-analytics/histogram?days=N
interface HistogramBucket {
  upperMs: number;
  count: number;
}

export interface HistogramResponse {
  buckets: HistogramBucket[];
  p50Ms: number;
  p95Ms: number;
  p99Ms: number;
}

// ── Cost & tokens by model ─────────────────────────────────────────────────
// GET /{projectId}/execution-analytics/cost?days=N
interface ModelCost {
  model: string;
  calls: number;
  tokens: number;
  costUsd: number;
  p95Ms: number;
}

export interface CostResponse {
  totalCostUsd: number;
  totalTokens: number;
  byModel: ModelCost[];
}

export interface AgentExecutionStats {
  agentRef: string;
  totalExecutions: number;
  verifiedCount: number;
  generatedCount: number;
  verifiedPercent: number;
  mostExecutedType: string;
  successRate: number;
}

type SourceType = "agent" | "workflow";

export interface ExecutionDetail {
  traceId: string;
  spanId: string;
  timestamp: string;
  executionType: ExecutionType;
  isVerified: boolean;
  // Source information
  sourceType: SourceType;
  sourceRef: string;
  // Common fields
  status: "success" | "error";
  durationMs: number;
  database?: string;
  output?: string;
  error?: string;
  // Type-specific fields
  // For semantic queries
  topic?: string;
  semanticQueryParams?: string;
  generatedSql?: string;
  // For omni queries
  integration?: string;
  endpoint?: string;
  // For SQL queries (verified)
  sql?: string;
  sqlRef?: string;
  // For SQL queries (generated)
  userQuestion?: string;
  automationRef?: string;
  agentRef?: string;
  toolInput?: string;
}
