//! `airway_load_audit` — aggregate root for per-extraction audit rows.
//!
//! Inserted with `status = "in_progress"` at the start of each load
//! and updated to `"completed"` / `"failed"` on terminal outcome. The
//! audit log is what tells a retry whether the prior attempt got past
//! destination commit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "airway_load_audit")]
pub struct Model {
    /// Load id (UUIDv4 string, generated by the airway engine).
    #[sea_orm(primary_key, auto_increment = false)]
    pub load_id: String,
    /// The workspace whose run performed this load. Every new row sets it,
    /// because `pipeline_name` alone is not unique across workspaces.
    ///
    /// `None` means the migration's backfill could not attribute the row, which
    /// covers more than an orphaned run: it reaches a load only through
    /// `airway_run_extensions`, so loads predating that table (before
    /// 2026-07-22) and any whose only link is a `load_started` event are NULL
    /// too. The migration says why that second route was declined
    /// (`super::migration`, `AddWorkspaceToLoadAudit`). So NULL is "not
    /// attributed", not "run is gone".
    pub workspace_id: Option<Uuid>,
    pub pipeline_name: String,
    /// Schema hash captured at load start — used to detect schema
    /// drift between attempts. `None` on the first-ever load for a
    /// pipeline (no prior schema in the state store yet).
    pub schema_hash: Option<String>,
    /// `in_progress` | `completed` | `failed`.
    pub status: String,
    /// Set only when `status = "failed"`.
    pub error_message: Option<String>,
    /// `true` when the run finished but some resources/tables were
    /// skipped (streaming per-batch commit). `status` stays
    /// `"completed"`; `partial` distinguishes a clean load from a
    /// completed-with-errors one. Defaults `false`.
    pub partial: bool,
    pub started_at: ChronoDateTimeUtc,
    pub finished_at: Option<ChronoDateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/// String status values as written to the column.
pub mod status {
    pub const IN_PROGRESS: &str = "in_progress";
    pub const COMPLETED: &str = "completed";
    pub const FAILED: &str = "failed";
}
