//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11
//!
//! # Every entity in this crate carries `#[sea_orm::model]`
//!
//! **A new entity needs that attribute above its `#[derive(..)]` line.** It is
//! what emits the strongly-typed `COLUMN` constant, letting a query read
//!
//! ```ignore
//! Entity::find().filter(COLUMN.enabled.eq(true))     // checked against `bool`
//! ```
//!
//! instead of the untyped
//!
//! ```ignore
//! Entity::find().filter(Column::Enabled.eq("banana")) // compiles; wrong at runtime
//! ```
//!
//! `DeriveEntityModel` on its own does **not** generate `COLUMN` — only this
//! attribute does — so an entity that omits it silently loses the typed form
//! while still compiling. The mistake surfaces later, at an unrelated call site
//! that cannot resolve `COLUMN`.
//!
//! The migration was **additive**: `Column::Foo` still works everywhere and both
//! spellings lower to identical SQL (asserted in `feature_flag`'s tests). Prefer
//! `COLUMN.foo` in new code; there is no need to churn existing call sites.
//!
//! ## `Model` vs `ModelEx` — the relation fields are not where they look
//!
//! A dense entity declares its relations inline:
//!
//! ```ignore
//! #[sea_orm(belongs_to, from = "org_id", to = "id")]
//! #[serde(skip)]
//! pub organizations: BelongsTo<super::organizations::Entity>,
//! ```
//!
//! but `#[sea_orm::model]` emits **two** structs from that. `Model` gets only
//! the scalar columns; `ModelEx` gets those plus the relations. So
//! `Model { .., organizations }` does not compile, and a handler serializing a
//! `Model` cannot leak a relation key into its response — that is structural,
//! not something the `#[serde(skip)]` buys.
//!
//! The `skip` is still load-bearing, on the other struct: `ModelEx` inherits
//! the derive list, and serializing a compound field requires
//! `E::ModelEx: Serialize` on the *related* entity. `users::Model` has no serde
//! derive by design, so without `skip` every entity pointing at it fails to
//! compile. `apps`' tests pin the resulting JSON shape.
//!
//! ## Scope, and the guard
//!
//! The heading is true of **this crate**. Sea-ORM entities also live in seven
//! others — `cameras`, `airhouse`, `agentic/{runtime,airway,automation,analytics}`
//! — and 23 of those still lack the attribute. `COLUMN` is simply unresolvable
//! there for now; that is pending work, not a decision.
//!
//! Because the failure mode is "still compiles", none of this is left to review
//! attention: `typed_column_guard` scans the whole workspace and fails on any
//! *new* entity that omits the attribute, with the 23 listed as a shrinking
//! backlog.

pub mod prelude;

#[cfg(test)]
mod typed_column_guard;

pub mod admin_assume_sessions;
pub mod airway_deployment_config;
pub mod airway_source_config;
pub mod api_keys;
pub mod app_admin_scope_orgs;
pub mod app_admins;
pub mod app_builds;
pub mod app_function_invocations;
pub mod app_functions;
pub mod app_members;
pub mod app_publish_tokens;
pub mod app_publishers;
pub mod app_storage_usage;
pub mod app_storage_usage_samples;
pub mod app_team_grants;
pub mod apps;
pub mod artifacts;
pub mod audit_events;
pub mod custom_app_event;
pub mod custom_app_migrations;
pub mod custom_app_view_event;
pub mod customer_app_automation_runs;
pub mod oidc_used_jti;
/// Back-compat alias for the renamed `customer_app_automation_runs` module.
/// Procedures/Workflows were renamed to Automations; existing call sites
/// referencing `entity::customer_app_procedure_runs` keep resolving here.
pub use customer_app_automation_runs as customer_app_procedure_runs;
pub mod chat_channel_members;
pub mod chat_channels;
pub mod chat_messages;
pub mod device_tokens;
pub mod document_ask_sessions;
pub mod document_ask_turns;
pub mod document_categories;
pub mod document_favorites;
pub mod document_versions;
pub mod documents;
pub mod feature_flag;
pub mod folders;
pub mod git_namespaces;
pub mod github_accounts;
pub mod location_external_ids;
pub mod locations;
pub mod logs;
pub mod messages;
pub mod metric_anomalies;
pub mod metric_monitor_coverage;
pub mod notifications;
pub mod org_billing;
pub mod org_frontline_members;
pub mod org_invitations;
pub mod org_kiosk_devices;
pub mod org_members;
pub mod org_role_members;
pub mod org_roles;
pub mod org_secrets;
pub mod org_subdomains;
pub mod org_team_members;
pub mod org_teams;
pub mod organizations;
pub mod partner_capabilities;
pub mod partner_grants;
pub mod partner_orgs;
pub mod partner_publish_consent;
pub mod partner_role_bindings;
pub mod quickbooks_oauth_states;
pub mod reconcile_configs;
pub mod run_sequences;
pub mod secrets;
pub mod settings;
pub mod slack_channel_defaults;
pub mod slack_installations;
pub mod slack_oauth_states;
pub mod slack_seen_events;
pub mod slack_threads;
pub mod slack_user_links;
pub mod slack_user_preferences;
pub mod stripe_webhook_events;
pub mod tasks;
pub mod test_case_human_verdicts;
pub mod test_project_runs;
pub mod test_run_cases;
pub mod test_run_sequences;
pub mod test_runs;
pub mod threads;
pub mod user_credentials;
pub mod users;
pub mod work_items;
pub mod workspace_health_state;
pub mod workspace_members;
pub mod workspace_oxy_lockdown;
pub mod workspaces;

// ── compile boundary (Phase 1.6a) ────────────────────────────────────
pub mod agent_definitions;
pub mod airway_pipelines;
pub mod app_definitions;
pub mod automation_definitions;
pub mod backfill_checkpoints;
pub mod backfill_ranges;
/// Back-compat alias for the renamed `automation_definitions` module
/// (formerly `procedure_definitions`). Keeps existing
/// `entity::procedure_definitions::*` call sites resolving.
pub use automation_definitions as procedure_definitions;
pub mod compiled_references;
pub mod monitor_configs;
pub mod revisions;
pub mod schema_migration_definitions;
pub mod semantic_topics;
pub mod semantic_views;
pub mod simulation_definitions;
pub mod simulation_run_fits;
pub mod simulation_run_periods;
pub mod simulation_runs;
pub mod verified_queries;
pub mod workspace_compiled_configs;
pub mod world_model_configs;
pub mod world_model_events;
