//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::{ActiveValue, entity::prelude::*};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub is_human: bool,
    pub thread_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub input_tokens: i32,
    pub output_tokens: i32,
    #[sea_orm(has_many)]
    pub artifacts: HasMany<super::artifacts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub threads: BelongsTo<super::threads::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            input_tokens: ActiveValue::Set(0),
            output_tokens: ActiveValue::Set(0),
            ..ActiveModelTrait::default()
        }
    }
}
