//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
pub enum WorkspaceProvider {
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "gitlab")]
    Gitlab,
    #[sea_orm(string_value = "bitbucket")]
    Bitbucket,
}

impl WorkspaceProvider {
    pub fn as_str(&self) -> &'static str {
        match self {
            WorkspaceProvider::Github => "github",
            WorkspaceProvider::Gitlab => "gitlab",
            WorkspaceProvider::Bitbucket => "bitbucket",
        }
    }

    pub fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "github" => Ok(WorkspaceProvider::Github),
            "gitlab" => Ok(WorkspaceProvider::Gitlab),
            "bitbucket" => Ok(WorkspaceProvider::Bitbucket),
            _ => Err(format!("Invalid workspace provider: {s}")),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum WorkspaceStatus {
    #[sea_orm(string_value = "ready")]
    #[default]
    Ready,
    #[sea_orm(string_value = "cloning")]
    Cloning,
    #[sea_orm(string_value = "failed")]
    Failed,
    /// Clone completed, but the repository is missing a `config.yml` at the
    /// workspace root — so it isn't an Oxy project. The user can open the IDE
    /// to add one; retrying the clone won't help.
    #[sea_orm(string_value = "not_oxy_project")]
    NotOxyProject,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "workspaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub git_namespace_id: Option<Uuid>,
    pub git_remote_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    /// Filesystem path to the workspace directory (contains config.yml).
    pub path: Option<String>,
    /// Last time this workspace was opened in the UI.
    pub last_opened_at: Option<DateTimeWithTimeZone>,
    /// User who created this workspace. Null for workspaces created before this field was added.
    pub created_by: Option<Uuid>,
    /// Organization this workspace belongs to. Null for workspaces created before multi-tenancy.
    pub org_id: Option<Uuid>,
    pub status: WorkspaceStatus,
    pub error: Option<String>,
    /// Operator-set monthly camera-fleet VLM spend ceiling, in USD
    /// micros. NULL = no budget configured (no banner shown). The
    /// Cameras dashboard projects month-to-date spend forward and
    /// alerts the operator when projection > budget.
    pub monthly_vlm_budget_micros: Option<i64>,
    /// Pointer to the compile boundary revision the runtime should
    /// read for this workspace. Phase 1.6a always leaves this NULL —
    /// `oxy compile` writes a successful `revisions` row but does
    /// NOT promote it here. Phase 1.6b will start promoting on each
    /// successful compile (Vercel-style atomic publish).
    pub current_revision_id: Option<Uuid>,
    /// The branch the repository's `origin/HEAD` names. Local git is the
    /// authority on a node with a checkout; this is what a node without one
    /// reads. NULL for a workspace with no remote, or not yet recorded.
    pub default_branch: Option<String>,
    /// Where the workspace root sits inside its repository, `/`-separated.
    /// NULL or empty = the repository root.
    pub repo_subdir: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "git_namespace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    #[serde(skip)]
    pub git_namespaces: BelongsTo<Option<super::git_namespaces::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "org_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    #[serde(skip)]
    pub organizations: BelongsTo<Option<super::organizations::Entity>>,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub workspace_members: HasMany<super::workspace_members::Entity>,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub slack_user_preferences: HasMany<super::slack_user_preferences::Entity>,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub slack_threads: HasMany<super::slack_threads::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
