//! Generates the route table `GET /api/_catalog` serves.
//!
//! This build script reads the router source of `oxy-app` and every surface
//! crate. It used to be `oxy-app`'s, which made editing any surface crate
//! re-run it and recompile all of `oxy-app`. Here, above both, an edit re-runs
//! only this script and relinks the binary (`internal-docs/domain-boundaries.md` S7).

// A build script's submodules resolve beside build.rs, and `build/` is
// gitignored workspace-wide — hence a sibling file with an explicit path.
#[path = "build_route_catalog.rs"]
mod route_catalog;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    emit_route_catalog();
}

/// Write `$OUT_DIR/route_catalog_generated.rs`: the endpoint table plus the
/// pre-rendered `--help` listing, so formatting it costs nothing at runtime
/// (clap builds every subcommand's help text on every `oxy` invocation).
fn emit_route_catalog() {
    let manifest_dir = std::path::PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set"),
    );
    // crates/route-catalog -> the workspace root.
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .unwrap_or(&manifest_dir)
        .to_path_buf();
    println!("cargo:rerun-if-changed=build_route_catalog.rs");

    let routes = route_catalog::collect(&repo_root);

    let mut out = String::from(
        "// @generated by crates/route-catalog/build_route_catalog.rs — do not edit.\n\
         pub static GENERATED_ROUTES: &[GeneratedRoute] = &[\n",
    );
    for r in &routes {
        out.push_str(&format!(
            "    GeneratedRoute {{ method: {:?}, path: {:?}, handler: {:?}, surface: {:?}, description: {:?}, note: {:?} }},\n",
            r.method, r.path, r.handler, r.surface, r.description, r.note
        ));
    }
    out.push_str("];\n\n");
    out.push_str("/// (surface id, display label, the credential it expects).\npub static GENERATED_SURFACES: &[(&str, &str, &str)] = &[\n");
    for (surface, label, credential) in route_catalog::SURFACES {
        out.push_str(&format!("    ({surface:?}, {label:?}, {credential:?}),\n"));
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// Source trees the walker reads, with how many routes each one\n\
         /// contributed. Lets a test check both that nothing declaring routes was\n\
         /// left out of them, and that every listed tree is actually reached.\n\
         pub static GENERATED_SCANNED_DIRS: &[(&str, usize)] = &[\n",
    );
    for dir in route_catalog::SOURCE_DIRS {
        let contributed = routes.iter().filter(|r| r.source_dir == *dir).count();
        out.push_str(&format!("    ({dir:?}, {contributed}),\n"));
    }
    out.push_str("];\n");

    let dest = std::path::PathBuf::from(
        std::env::var("OUT_DIR").expect("OUT_DIR is always set for a build script"),
    )
    .join("route_catalog_generated.rs");
    std::fs::write(&dest, out).expect("write route catalog");
}
