//! The HTTP route table, as data.
//!
//! Axum keeps no route table at runtime — the router is a tower service, not a
//! list — so the catalog is extracted from the router source at build time by
//! `oxy-route-catalog`'s build script (`crates/route-catalog/build_route_catalog.rs`)
//! and handed in by the composition root as a [`RouteCatalog`]. That is what lets
//! `GET /api/_catalog` — and so `oxyc routes` — enumerate the API without a
//! hand-maintained list that rots.
//!
//! # Scope
//!
//! **The `/api` and `/external/api` surfaces**, which is what `oxyc api` can
//! call. `paths_are_well_formed` enforces the boundary, so these are excluded
//! by construction, not by accident:
//!
//! - `ANY /customer-apps/{*path}` — the custom-app bundle serve tree, mounted
//!   at the top level because it is browser-facing (`cli/commands/serve.rs`).
//! - `/apidoc` and `/apidoc/openapi.json` — Swagger UI and the spec itself.
//! - The worker health port (`/healthz`, `/readyz`, `/metrics`), served only
//!   when `oxy worker --health-port` is set.
//! - `internal_api_router` — the unauthenticated loopback port
//!   (`--internal-port`), which mirrors API routes without auth.
//!
//! A route inside those bounds that is *missing* is a walker bug. A route
//! outside them was never in scope.
//!
//! The tests below are the completeness gate: they fail if the walk stops
//! reaching a surface or a landmark route, so a router refactor the lexical
//! walker can no longer follow shows up in CI rather than as a quietly
//! shrinking `oxyc routes`.

use serde::Serialize;

use super::role_manifest;

/// One endpoint, exactly as the router mounts it.
pub struct GeneratedRoute {
    /// Uppercase HTTP method (`GET`, `POST`, …; `ANY` for method-agnostic mounts).
    pub method: &'static str,
    /// Full path pattern including the `/api` prefix, e.g.
    /// `/api/{workspace_id}/threads`.
    pub path: &'static str,
    /// The handler the route dispatches to, for cross-referencing the source.
    /// Empty when the handler is a closure or another non-path expression.
    pub handler: &'static str,
    /// Which authentication surface the route sits on — see [`surfaces`].
    pub surface: &'static str,
    /// The handler's own doc comment, flattened to one line — what the
    /// endpoint does. Empty when the handler carries none (roughly half of
    /// them do not).
    pub description: &'static str,
    /// The comment the router source carries on this mount — usually *why* the
    /// route sits where it does, and the gotcha that put it there. Empty when
    /// the mount has none.
    ///
    /// Both `description` and `note` are harvested at build time from the
    /// engineers' own comments, so they are a hint, never a contract. The
    /// schemas live in the OpenAPI document (`oxyc openapi`).
    pub note: &'static str,
}

/// The generated table, as the composition root hands it in.
///
/// Generated by `oxy-route-catalog`'s build script, which sits ABOVE this
/// crate. It scans every surface crate's source; were it this crate's build
/// script (as it once was), editing any surface crate would re-run it and
/// recompile all of `oxy-app` (`internal-docs/domain-boundaries.md` S7). So
/// `oxy-app` owns the type and the handler, and `oxy-server` passes the data
/// through [`SurfaceSeams`](super::router::SurfaceSeams) — explicitly, never a
/// global; a composition that forgets it serves an empty catalog, which
/// `oxy-server`'s seam test catches.
#[derive(Clone, Copy, Default)]
pub struct RouteCatalog {
    /// Every route on the `/api` and `/external/api` surfaces, sorted by
    /// surface then path. See the module docs for what those bounds leave out.
    pub routes: &'static [GeneratedRoute],
    /// Surfaces in display order: `(id, label, the credential it expects)`.
    pub surfaces: &'static [(&'static str, &'static str, &'static str)],
}

/// A route rendered for machine consumption (`oxyc routes --json`).
#[derive(Serialize)]
pub struct RouteDescription {
    pub method: &'static str,
    pub path: &'static str,
    pub surface: &'static str,
    /// The credential this surface expects, spelled out rather than implied.
    pub credential: &'static str,
    /// `{…}` segments of the path, in order — the values a caller substitutes.
    pub path_parameters: Vec<&'static str>,
    pub description: &'static str,
    pub note: &'static str,
    pub handler: &'static str,
    /// `ide-only` when the handler needs the workspace working copy / `.git`,
    /// so a stateless serve replica forwards or refuses it; `worker-only` for
    /// the queue-drainer surface; `fleet-ok` otherwise. Straight from
    /// [`role_manifest`], the same table the server enforces.
    pub role: &'static str,
}

/// The `{name}` (and `{*name}`) segments of a path pattern, in order.
pub fn path_parameters(path: &'static str) -> Vec<&'static str> {
    path.split('/')
        .filter_map(|seg| {
            seg.strip_prefix('{')?
                .strip_suffix('}')
                .map(|n| n.trim_start_matches('*'))
        })
        .collect()
}

/// The fields [`search`] matches a needle against.
///
/// Named once so the doc on `/api/_catalog`'s `?filter=`, the client's own
/// local filter, and the test that checks them all read the same list. They
/// had drifted: this matched three fields, the endpoint's doc claimed four,
/// and the TypeScript client matched four — so `?filter=pre-aggregation`
/// returned nothing while `oxyc routes pre-aggregation`, which fetches
/// everything and narrows locally, returned the matching routes. Two answers
/// to one question, from one tool.
pub fn searchable_fields(route: &GeneratedRoute) -> [&'static str; 4] {
    [route.method, route.path, route.surface, route.description]
}

impl RouteCatalog {
    /// Routes whose method, path, surface or description contains `needle`
    /// (case-insensitive), or every route when `needle` is `None`.
    pub fn search(&self, needle: Option<&str>) -> Vec<&'static GeneratedRoute> {
        let needle = needle.map(str::to_lowercase);
        self.routes
            .iter()
            .filter(|r| match &needle {
                None => true,
                Some(n) => searchable_fields(r)
                    .iter()
                    .any(|field| field.to_lowercase().contains(n.as_str())),
            })
            .collect()
    }

    pub fn describe(&self, route: &'static GeneratedRoute) -> RouteDescription {
        RouteDescription {
            method: route.method,
            path: route.path,
            surface: route.surface,
            credential: self
                .surfaces
                .iter()
                .find(|(id, _, _)| *id == route.surface)
                .map(|(_, _, credential)| *credential)
                .unwrap_or_default(),
            path_parameters: path_parameters(route.path),
            description: route.description,
            note: route.note,
            handler: route.handler,
            role: role_manifest::classify(route.method, route.path).as_str(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_parameters_are_extracted_in_order() {
        assert_eq!(
            path_parameters("/api/{workspace_id}/threads/{id}/messages"),
            vec!["workspace_id", "id"]
        );
        assert_eq!(path_parameters("/api/health"), Vec::<&str>::new());
        // Axum's catch-all keeps its name without the star.
        assert_eq!(
            path_parameters("/api/{workspace_id}/cameras/{cam_id}/preview/hls/{*tail}"),
            vec!["workspace_id", "cam_id", "tail"]
        );
    }
}
