import { CheckCircle2, XCircle } from "lucide-react";
import type React from "react";
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/shadcn/card";
import { Spinner } from "@/components/ui/shadcn/spinner";

/**
 * `/cli-auth` — the browser side of `oxyc login`.
 *
 * The CLI opens this page with `?port=<loopback>&state=<nonce>`. If the user
 * has a session, we hand the existing `auth_token` to the CLI's loopback
 * listener and the CLI caches it. If not, we bounce through the normal login
 * and return here.
 *
 * Security: the callback URL is only ever `http://127.0.0.1:<port>` built
 * from the integer `port` param — never an arbitrary URL — so this can't be
 * abused as an open redirect to leak the token off-box. The `state` nonce
 * (generated by the CLI) guards the loopback against unsolicited hits.
 */
const CliAuth: React.FC = () => {
  const [params] = useSearchParams();
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  useEffect(() => {
    const port = params.get("port");
    const state = params.get("state");
    if (!port || !/^\d+$/.test(port) || !state) {
      setError("Invalid CLI login request (missing or malformed port/state).");
      return;
    }

    const returnTo = `${window.location.origin}/cli-auth?port=${port}&state=${encodeURIComponent(
      state
    )}`;
    const toLogin = () => {
      window.location.href = `/login?return_to=${encodeURIComponent(returnTo)}`;
    };

    const token = localStorage.getItem("auth_token");
    if (!token) {
      toLogin();
      return;
    }

    // Verify the token is a *currently valid* session before handing it to the
    // CLI. A stale token (e.g. oxy restarted with a new signing key) would
    // otherwise be handed over and rejected, dead-ending the CLI with "token
    // did not resolve to a user". `/api/user` returns the user when valid and
    // `null` when not, so on null we bounce through login to mint a fresh one.
    let cancelled = false;
    // Cannot reject: the whole body is inside the try/catch, which falls back to login.
    void (async () => {
      try {
        const res = await fetch("/api/user", {
          headers: { Authorization: `Bearer ${token}` },
          credentials: "include"
        });
        const user = res.ok ? await res.json() : null;
        if (cancelled) return;
        if (!user) {
          toLogin();
          return;
        }
        // Loopback handoff. Top-level navigation to an http loopback is allowed
        // even from an https origin (loopback is exempt from mixed-content
        // blocking), so this works on both local and cloud.
        const callback = `http://127.0.0.1:${port}/callback?token=${encodeURIComponent(
          token
        )}&state=${encodeURIComponent(state)}`;
        setDone(true);
        window.location.href = callback;
      } catch {
        if (!cancelled) toLogin();
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [params]);

  return (
    <div className='flex min-h-screen w-full items-center justify-center bg-background p-4'>
      <Card className='w-full max-w-md'>
        <CardHeader className='text-center'>
          <div className='mb-4 flex justify-center'>
            {error ? (
              <XCircle className='h-12 w-12 text-destructive' />
            ) : done ? (
              <CheckCircle2 className='h-12 w-12 text-primary' />
            ) : (
              <Spinner className='h-12 w-12' />
            )}
          </div>
          <CardTitle className='text-2xl'>
            {error ? "CLI login failed" : done ? "Login complete" : "Completing CLI login…"}
          </CardTitle>
          <CardDescription>
            {error ??
              (done
                ? "Returning to your terminal. You can close this tab."
                : "Handing your session back to the oxy CLI.")}
          </CardDescription>
        </CardHeader>
        <CardContent />
      </Card>
    </div>
  );
};

export default CliAuth;
