[package]
name = "entity"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
sea-orm = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
indexmap = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lib]
name = "entity"
path = "src/lib.rs"
