import type React from "react";
import { useEffect, useState } from "react";
import { type LegacyRequest, loginUrl, returnToUrl, tokenCallbackUrl } from "../cliAuthRequest";
import { leaveTo, readCliSession } from "../cliSession";
import CliAuthCard from "./CliAuthCard";

/**
 * The flow an oxyc that predates PKCE expects: `?port=<loopback>&state=<nonce>` and nothing else.
 * If the user has a session, the existing `auth_token` goes straight to the CLI's loopback
 * listener, with no click. If not, bounce through the normal login and return here.
 *
 * Unchanged from before PKCE existed, so older oxyc versions keep working. The `state` nonce
 * (generated by the CLI) guards the loopback against unsolicited hits.
 */
const LegacyHandoff: React.FC<{ request: LegacyRequest }> = ({ request }) => {
  const [done, setDone] = useState(false);

  useEffect(() => {
    const toLogin = () => leaveTo(loginUrl(returnToUrl(window.location.origin, request)));

    let cancelled = false;
    // Cannot reject: the whole body is inside the try/catch, which falls back to login.
    void (async () => {
      try {
        const session = await readCliSession();
        if (cancelled) return;
        if (!session) {
          toLogin();
          return;
        }
        // Loopback handoff. Top-level navigation to an http loopback is allowed
        // even from an https origin (loopback is exempt from mixed-content
        // blocking), so this works on both local and cloud.
        setDone(true);
        leaveTo(tokenCallbackUrl(request, session.token));
      } catch {
        if (!cancelled) toLogin();
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [request]);

  return (
    <CliAuthCard
      status={done ? "done" : "working"}
      title={done ? "Login complete" : "Completing CLI login…"}
      description={
        done
          ? "Returning to your terminal. You can close this tab."
          : "Handing your session back to the oxy CLI."
      }
    />
  );
};

export default LegacyHandoff;
